esphome:
  name: ws2812b-led
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_ota_password

ota:
  password: !secret esphome_ota_password

output:
  - id: gpio_builtin_led
    platform: gpio
    inverted: True
    pin: D4

light:
  - platform: binary
    name: "Builtin LED"
    id: builtin_led
    output: gpio_builtin_led

light:
  - platform: fastled_clockless
    chipset: WS2812b
    pin: D3
    num_leds: 6
    rgb_order: GRB
    name: rgb
    id: rgb

  - platform: partition
    name: "Partition Light 0"
    segments:
      - id: rgb
        from: 0
        to: 0
  - platform: partition
    name: "Partition Light 1"
    segments:
      - id: rgb
        from: 1
        to: 1
  - platform: partition
    name: "Partition Light 2"
    segments:
      - id: rgb
        from: 2
        to: 2
  - platform: partition
    name: "Partition Light 3"
    segments:
      - id: rgb
        from: 3
        to: 3
  - platform: partition
    name: "Partition Light 4"
    segments:
      - id: rgb
        from: 4
        to: 4
  - platform: partition
    name: "Partition Light 5"
    segments:
      - id: rgb
        from: 5
        to: 5