esphome:
  name: led_button
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_ota_password

ota:
  password: !secret esphome_ota_password

output:
  - id: gpio_led
    platform: gpio
    inverted: True
    pin: D1

light:
  - platform: binary
    name: "LED"
    id: led
    output: gpio_led

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    on_press:
      then:
        - light.toggle: led
