esphome:
  name: ldr
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_ota_password

ota:
  password: !secret esphome_ota_password

output:
  - id: gpio_builtin_led
    platform: gpio
    inverted: True
    pin: D4

light:
  - platform: binary
    name: "Builtin LED"
    id: builtin_led
    output: gpio_builtin_led

sensor:
  - platform: adc
    pin: A0
    id: ldr_sensor
    name: "LDR sensor"
    update_interval: 1s
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: ldr_sensor
              below: 0.55
          then:
            - light.turn_on: builtin_led
          else:
            - light.turn_off: builtin_led